SDKVERSION = 5.0

include theos/makefiles/common.mk

LIBRARY_NAME = FacebookWeeApp

FacebookWeeApp_FILES = FacebookWeeApp.mm
FacebookWeeApp_INSTALL_PATH = /System/Library/WeeAppPlugins/FacebookWeeApp.bundle

FacebookWeeApp_FRAMEWORKS = UIKit Foundation
FacebookWeeApp_PRIVATE_FRAMEWORKS = BulletinBoard

include $(THEOS_MAKE_PATH)/library.mk

