@interface SBBulletinListController : NSObject <BBObserverDelegate, SBBulletinListViewDelegate, SBBulletinWindowClient> {
	BBObserver* _observer;
	NSMutableDictionary* _enabledSectionsByID;
	NSMutableArray* _visibleSectionIDs;
	NSArray* _possibleSectionIDs;
	unsigned _sectionOrderRule;
	NSMutableArray* _weeApps;
	NSMutableDictionary* _headerViewsBySectionID;
	SBBulletinListView* _listView;
	BOOL _listViewTableViewHasLoaded;
	BOOL _listViewIsActive;
	BOOL _weeAppFullViewsHaveBeenLoaded;
	SBApplication* _coveredApplication;
	BOOL _grabbed;
	float _grabbedY;
}
+(id)_sharedInstanceCreateIfNecessary:(BOOL)necessary;
+(id)sharedInstance;
+(id)sharedInstanceIfExists;
-(id)init;
-(void)dealloc;
-(id)listView;
-(float)listViewHeight;
-(void)prepareToShowListViewAnimated:(BOOL)showListViewAnimated aboveBanner:(BOOL)banner;
-(void)prepareToHideListViewAnimated:(BOOL)hideListViewAnimated;
-(void)positionListViewAtY:(float)y;
-(void)showListViewAnimated:(BOOL)animated withAnimations:(id)animations completion:(id)completion;
-(void)hideListViewAnimated:(BOOL)animated withAnimations:(id)animations completion:(id)completion;
-(void)showListViewAnimated:(BOOL)animated;
-(void)hideListViewAnimated:(BOOL)animated;
-(void)_setListViewActive:(BOOL)active;
-(void)_tearDownView;
-(void)_touchInList:(id)list;
-(BOOL)listViewIsActive;
-(void)_sortVisibleSectionIDsForManualSortOrder;
-(void)_sortVisibleSectionIDsForAutomaticSortOrder;
-(void)_sortVisibleSectionIDs;
-(unsigned)_insertVisibleSectionIDForManualSortOrder:(id)manualSortOrder;
-(unsigned)_insertVisibleSectionIDForAutomaticSortOrder:(id)automaticSortOrder;
-(unsigned)_insertVisibleSectionID:(id)anId;
-(id)_weeAppForSectionID:(id)sectionID;
-(void)_removeWeeAppForSectionID:(id)sectionID;
-(id)_weeAppForSectionID:(id)sectionID bundlePath:(id)path;
-(void)_updateSectionForSectionInfo:(id)sectionInfo withCompletion:(id)completion;
-(void)_loadSections;
-(id)_sectionAtIndex:(unsigned)index;
-(id)_bulletinAtIndexPath:(id)indexPath;
-(id)_indexPathForBulletin:(id)bulletin;
-(float)_rowHeightForBulletin:(id)bulletin;
-(float)_headerHeightForSection:(id)section;
-(void)_clearSection:(id)section;
-(void)_handlePanUngrabWithVelocity:(CGPoint)velocity;
-(void)_updateForPanBeganOrMoved:(id)panBeganOrMoved;
-(void)_updateForPanEnded:(id)panEnded;
-(void)_updateForPanCanceled;
-(void)handleTap:(id)tap;
-(void)handlePan:(id)pan;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(void)bulletinWindowWillRotateToOrientation:(int)bulletinWindow;
-(void)bulletinWindowIsAnimatingRotationToOrientation:(int)orientation;
-(void)bulletinWindowDidRotateFromOrientation:(int)bulletinWindow;
-(void)bulletinWindowStoppedBeingBusy;
-(void)_fixCellSeparatorAboveRow:(unsigned)row inSection:(id)section sectionIndex:(unsigned)index;
-(void)_fixLastRowSeparatorsInAllSections;
-(void)_updateModelAndTableViewForAddition:(id)addition;
-(void)_updateModelAndTableViewForModification:(id)modification originalIndex:(unsigned)index;
-(void)_updateModelAndTableViewForRemoval:(id)removal originalIndex:(unsigned)index;
-(void)observer:(id)observer addBulletin:(id)bulletin forFeed:(unsigned)feed;
-(void)observer:(id)observer modifyBulletin:(id)bulletin;
-(void)observer:(id)observer removeBulletin:(id)bulletin;
-(void)observer:(id)observer updateSectionOrderRule:(unsigned)rule;
-(void)observer:(id)observer updateSectionOrder:(id)order;
-(void)observer:(id)observer updateSectionInfo:(id)info;
-(BOOL)observerShouldFetchAttachmentImageBeforeBulletinDelivery:(id)observer;
-(BOOL)observerShouldFetchAttachmentSizeBeforeBulletinDelivery:(id)observer;
-(id)observer:(id)observer thumbnailSizeConstraintsForAttachmentType:(int)attachmentType;
-(id)observer:(id)observer attachmentImageForType:(int)type thumbnailData:(id)data;
-(CGSize)observer:(id)observer attachmentSizeForType:(int)type thumbnailWidth:(float)width height:(float)height;
-(int)testAttachmentType;
-(id)testGenerateThumbnailDataForType:(int)type constraints:(id)constraints;
-(float)testThumbnailAspectRatioForType:(int)type;
-(int)numberOfSectionsInTableView:(id)tableView;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(BOOL)_useTopPaddingForWeeAppAtSectionIndex:(unsigned)sectionIndex;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)_separatorStyleForRow:(unsigned)row inSection:(id)section sectionIndex:(unsigned)index;
-(id)_bulletinCellForSection:(id)section sectionIndex:(unsigned)index row:(unsigned)row tableView:(id)view;
-(id)_weeAppCellForSection:(id)section sectionIndex:(unsigned)index tableView:(id)view;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)tableViewDidFinishReload:(id)tableView;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)runScrollTest:(id)test iterations:(int)iterations delta:(int)delta;
-(void)finishedScrollTest;
@end
