include theos/makefiles/common.mk

TWEAK_NAME = FacebookWeeAppHooker

FacebookWeeAppHooker_FILES = Tweak.xm
FacebookWeeAppHooker_INSTALL_PATH = /Library/FacebookWeeAppHooker/
FacebookWeeAppHooker_FRAMEWORKS = UIKit Foundation

include $(THEOS_MAKE_PATH)/tweak.mk
