include theos/makefiles/common.mk

TWEAK_NAME = FacebookWeeAppHooker

FacebookWeeAppHooker_FILES = Tweak.xm
FacebookWeeAppHooker_INSTALL_PATH = /Library/WeeFacebookHooker/
FacebookWeeAppHooker_FRAMEWORKS = UIKit Foundation
FacebookWeeAppHooker_LDFLAGS = -lsubstrate

include $(THEOS_MAKE_PATH)/tweak.mk
